Repository vkamiansky/yandex-dialogs-inventory, pull requests merged in 2019-05, with the labels that each got.

#10 Added example integration tests
  example/WebAPI/AliceTestApi.sln
  example/WebAPI/TestApi.IntegrationTests/TestApi.IntegrationTests.csproj
  example/WebAPI/TestApi.IntegrationTests/UnitTest1.cs
  example/WebAPI/TestApi/Controllers/ValuesController.cs
  example/WebAPI/TestApi/Program.cs
  example/WebAPI/TestApi/Properties/launchSettings.json
  example/WebAPI/TestApi/Startup.cs
  example/WebAPI/TestApi/TestApi.csproj
  example/WebAPI/TestApi/appsettings.Development.json
  example/WebAPI/TestApi/appsettings.json
Labels: enhancement, good first issue

#11 Added Json
  example/WebAPI/TestApi/Controllers/ValuesController.cs
  example/WebAPI/TestApi/UserInput.cs
Labels: enhancement

#13 Moved Tests to src
  src/AliceInventory.IntegrationTests/AliceInventory.IntegrationTests.csproj
  src/AliceInventory.IntegrationTests/UnitTest1.cs
  src/AliceInventory.sln
Labels: enhancement

#15 Feature/post integration tests
  src/AliceInventory.IntegrationTests/PostTest.cs
  src/AliceInventory/Controllers/ValuesController.cs
Labels: enhancement

#17 Added main logic interface
  .vscode/solution-explorer/class.cs-template
  .vscode/solution-explorer/class.ts-template
  .vscode/solution-explorer/class.vb-template
  .vscode/solution-explorer/default.ts-template
  .vscode/solution-explorer/enum.cs-template
  .vscode/solution-explorer/interface.cs-template
  .vscode/solution-explorer/interface.ts-template
  .vscode/solution-explorer/template-list.json
  .vscode/solution-explorer/template-parameters.js
  .vscode/tasks.json
  src/AliceInventory.IntegrationTests/InventoryControllerTest.cs
  src/AliceInventory/Alice/Alice.cs
  src/AliceInventory/Alice/Extensions.cs
  src/AliceInventory/Alice/Models.cs
  src/AliceInventory/ChatResponse.cs
  src/AliceInventory/Controllers/AliceRequest.cs
  src/AliceInventory/Controllers/AliceResponse.cs
  src/AliceInventory/Controllers/Button.cs
  src/AliceInventory/Controllers/InventoryController.cs
  src/AliceInventory/Controllers/Meta.cs
  src/AliceInventory/Controllers/Request.cs
  src/AliceInventory/Controllers/Response.cs
  src/AliceInventory/Controllers/Session.cs
  src/AliceInventory/Data/Entry.cs
  src/AliceInventory/Data/IInventoryStorage.cs
  src/AliceInventory/Data/UnitOfMeasure.cs
  src/AliceInventory/Google/QueryModels.cs
  src/AliceInventory/Google/ResponceModels.cs
  src/AliceInventory/Logic/Entry.cs
  src/AliceInventory/Logic/ICommandCache.cs
  src/AliceInventory/Logic/IInputParserService.cs
  src/AliceInventory/Logic/IInventoryDialogService.cs
  src/AliceInventory/Logic/InputProcessingCommand.cs
  src/AliceInventory/Logic/InputProcessingResult.cs
  src/AliceInventory/Logic/ProcessingCommand.cs
  src/AliceInventory/Logic/ProcessingResult.cs
  src/AliceInventory/Logic/UnitOfMeasure.cs
  src/AliceInventory/Parser/Entry.cs
  src/AliceInventory/Parser/IDataStorage.cs
  src/AliceInventory/Parser/Parser.cs
  src/AliceInventory/Parser/SessionManager.cs
  src/AliceInventory/Parser/Storage.cs
  src/AliceInventory/Parser/Unit.cs
  src/AliceInventory/Parser/UserSession.cs
Labels: enhancement, Алиса

#24 Delete unnecessary files inside directory .vscode and configure debug for AliceInventory
  .gitignore
  .vscode/launch.json
  .vscode/solution-explorer/class.cs-template
  .vscode/solution-explorer/class.ts-template
  .vscode/solution-explorer/class.vb-template
  .vscode/solution-explorer/default.ts-template
  .vscode/solution-explorer/enum.cs-template
  .vscode/solution-explorer/interface.cs-template
  .vscode/solution-explorer/interface.ts-template
  .vscode/solution-explorer/template-list.json
  .vscode/solution-explorer/template-parameters.js
  .vscode/tasks.json
Labels: bug

#25 Unused files removed
  src/AliceInventory/ChatResponse.cs
  src/AliceInventory/Parser/Entry.cs
  src/AliceInventory/Parser/IDataStorage.cs
  src/AliceInventory/Parser/Parser.cs
  src/AliceInventory/Parser/SessionManager.cs
  src/AliceInventory/Parser/Storage.cs
  src/AliceInventory/Parser/Unit.cs
  src/AliceInventory/Parser/UserSession.cs
Labels: bug

#26 Added CommandCache + unit tests
  src/AliceInventory.UnitTests/AliceInventory.UnitTests.csproj
  src/AliceInventory.UnitTests/CommandCacheTests.cs
  src/AliceInventory.sln
  src/AliceInventory/Logic/CommandCache.cs
Labels: enhancement, logic

#27 Added InventoryDialogService initial implementation + unit test
  src/AliceInventory.UnitTests/AliceInventory.UnitTests.csproj
  src/AliceInventory.UnitTests/CommandCacheTests.cs
  src/AliceInventory.UnitTests/InventoryDialogServiceTests.cs
  src/AliceInventory/Data/UnitOfMeasure.cs
  src/AliceInventory/Logic/Converter.cs
  src/AliceInventory/Logic/InventoryDialogService.cs
  src/AliceInventory/Startup.cs
Labels: enhancement, logic

#28 IInventoryStorage implemented by DictionaryStorage
  src/AliceInventory.UnitTests/InventoryDialogServiceTests.cs
  src/AliceInventory/Data/DictionaryStorage.cs
  src/AliceInventory/Data/IInventoryStorage.cs
Labels: data, enhancement

#33 AI.UT.IDST. Add ProcessInputDeleteTest()
  src/AliceInventory.UnitTests/InventoryDialogServiceTests.cs
Labels: logic

#35 Added HEAD-method in Alice controller.
  src/AliceInventory.IntegrationTests/InventoryControllerTest.cs
  src/AliceInventory/Controllers/InventoryController.cs
Labels: api, enhancement

#29 Input Processing Results expanding
  src/AliceInventory/Logic/InputProcessingCommand.cs
  src/AliceInventory/Logic/InputProcessingResult.cs
Labels: logic

#32 Feature/input parser service
  src/AliceInventory.UnitTests/AliceInventory.UnitTests.csproj
  src/AliceInventory.UnitTests/InputParserServiceTest.cs
  src/AliceInventory/Logic/InputParserService.cs
  src/AliceInventory/Logic/InputProcessingCommand.cs
  src/AliceInventory/Startup.cs
Labels: logic

#39 Add globalization in Feature/input parser service
  src/AliceInventory.UnitTests/InputParserServiceTest.cs
  src/AliceInventory.UnitTests/InventoryDialogServiceTests.cs
  src/AliceInventory/Logic/IInputParserService.cs
  src/AliceInventory/Logic/IInventoryDialogService.cs
  src/AliceInventory/Logic/InputParserService.cs
  src/AliceInventory/Logic/InputProcessingCommand.cs
  src/AliceInventory/Logic/InventoryDialogService.cs
Labels: logic

#41 Feature/parser improvements
  src/AliceInventory.UnitTests/CommandCacheTests.cs
  src/AliceInventory.UnitTests/InputParserServiceTest.cs
  src/AliceInventory/Logic/InputParserService.cs
  src/AliceInventory/Logic/InputProcessingResult.cs
  src/AliceInventory/Logic/InventoryDialogService.cs
Labels: logic

#42 Pre master
  src/AliceInventory.IntegrationTests/AliceInventory.IntegrationTests.csproj
  src/AliceInventory.IntegrationTests/InventoryControllerTest.cs
  src/AliceInventory.UnitTests/AliceResponseRenderTest.cs
  src/AliceInventory.UnitTests/InventoryDialogServiceTests.cs
  src/AliceInventory/AliceInventory.csproj
  src/AliceInventory/Controllers/InventoryController.cs
  src/AliceInventory/Controllers/Request.cs
  src/AliceInventory/Logic/AliceResponseRender/AliceResponseRendererHelper.cs
  src/AliceInventory/Logic/AliceResponseRender/ResponseFormat.cs
  src/AliceInventory/Logic/AliceResponseRender/ResponseTemplate.cs
  src/AliceInventory/Logic/AliceResponseRender/TextAndSpeechTemplate.cs
  src/AliceInventory/Logic/ConfigurationService.cs
  src/AliceInventory/Logic/Email/AliceEmailService.cs
  src/AliceInventory/Logic/Email/EmailHost.cs
  src/AliceInventory/Logic/Email/EmailService.cs
  src/AliceInventory/Logic/Email/IAliceEmailService.cs
  src/AliceInventory/Logic/Extensions.cs
  src/AliceInventory/Logic/IConfigurationService.cs
  src/AliceInventory/Logic/InputParserService.cs
  src/AliceInventory/Logic/InventoryDialogService.cs
  src/AliceInventory/Logic/ProcessingResult.cs
  src/AliceInventory/Startup.cs
Labels: Алиса

#40 Feature/alice response render
  src/AliceInventory.UnitTests/InputParserServiceTest.cs
  src/AliceInventory.UnitTests/InventoryDialogServiceTests.cs
  src/AliceInventory/Logic/IInputParserService.cs
  src/AliceInventory/Logic/IInventoryDialogService.cs
  src/AliceInventory/Logic/InputParserService.cs
  src/AliceInventory/Logic/InputProcessingCommand.cs
  src/AliceInventory/Logic/InventoryDialogService.cs
Labels: analysis, Алиса

#46 Create LICENSE
  LICENSE
Labels: help wanted

#57 Added configuration test method
  src/AliceInventory/AliceInventory.csproj
  src/AliceInventory/Controllers/InventoryController.cs
  src/AliceInventory/Logic/ConfigurationService.cs
  src/AliceInventory/Logic/IConfigurationService.cs
Labels: api, enhancement, logic

#58 Config integration testing temporarily disabled.
  src/AliceInventory.IntegrationTests/InventoryControllerTest.cs
  src/AliceInventory/Logic/ConfigurationService.cs
Labels: bug

#59 A more verbose config error text.
  src/AliceInventory/Controllers/InventoryController.cs
  src/AliceInventory/Logic/ConfigurationService.cs
  src/AliceInventory/Logic/IConfigurationService.cs
Labels: bug

#50 Fix inputParserService
  src/AliceInventory.UnitTests/InputParserServiceTest.cs
  src/AliceInventory/Logic/AliceResponseRender/AliceResponseRendererHelper.cs
  src/AliceInventory/Logic/Extensions.cs
  src/AliceInventory/Logic/InputParserService.cs
  src/AliceInventory/Logic/InputProcessingCommand.cs
  src/AliceInventory/Logic/InventoryDialogService.cs
  src/AliceInventory/Logic/Parser/CommandTemplate.cs
  src/AliceInventory/Logic/Parser/CommandTemplateWithEmail.cs
  src/AliceInventory/Logic/Parser/CommandTemplateWithEntry.cs
  src/AliceInventory/Logic/Parser/InputParserService.cs
  src/AliceInventory/Logic/Parser/RegexHelper.cs
  src/AliceInventory/Startup.cs
Labels: logic, Алиса
