Repository vkamiansky/yandex-dialogs-inventory, pull requests merged in 2019-07, with the labels that each got.

#84 AppVeyor webhook badges
  README.md
Labels: bug

#86 Reengineering + refactoring + logic test coverage
  src/AliceInventory.IntegrationTests/AliceInventory.IntegrationTests.csproj
  src/AliceInventory.UnitTests/AliceInventory.UnitTests.csproj
  src/AliceInventory.UnitTests/AliceResponseRenderTest.cs
  src/AliceInventory.UnitTests/CommandCacheTests.cs
  src/AliceInventory.UnitTests/InputParserServiceTest.cs
  src/AliceInventory.UnitTests/InventoryDialogServiceTests.cs
  src/AliceInventory.UnitTests/ResultCacheTests.cs
  src/AliceInventory/AliceInventory.csproj
  src/AliceInventory/Controllers/AliceResponseRender/AliceResponseRendererHelper.cs
  src/AliceInventory/Controllers/AliceResponseRender/ResponseFormat.cs
  src/AliceInventory/Controllers/AliceResponseRender/ResponseTemplate.cs
  src/AliceInventory/Controllers/AliceResponseRender/TextAndSpeechTemplate.cs
  src/AliceInventory/Controllers/Extensions.cs
  src/AliceInventory/Controllers/InventoryController.cs
  src/AliceInventory/Data/DictionaryUserDataStorage.cs
  src/AliceInventory/Data/Entry.cs
  src/AliceInventory/Data/IUserDataStorage.cs
  src/AliceInventory/Data/UnitOfMeasure.cs
  src/AliceInventory/Logic/Cache/IResultCache.cs
  src/AliceInventory/Logic/Cache/ResultCache.cs
  src/AliceInventory/Logic/Configuration/ConfigurationService.cs
  src/AliceInventory/Logic/Configuration/IConfigurationService.cs
  src/AliceInventory/Logic/Core/Errors/EmptyEntryListError.cs
  src/AliceInventory/Logic/Core/Errors/EntryNotFoundInDatabaseError.cs
  src/AliceInventory/Logic/Core/Errors/MailIsEmptyError.cs
  src/AliceInventory/Logic/Core/Errors/NotEnoughEntryToDeleteError.cs
  src/AliceInventory/Logic/Core/Exceptions/UnexpectedNullOrEmptyStringException.cs
  src/AliceInventory/Logic/Core/Exceptions/UnexpectedTypeException.cs
  src/AliceInventory/Logic/Core/IInventoryDialogService.cs
  src/AliceInventory/Logic/Core/InventoryDialogService.cs
  src/AliceInventory/Logic/Core/ProcessingCommand.cs
  src/AliceInventory/Logic/Core/ProcessingCommandType.cs
  src/AliceInventory/Logic/Core/ProcessingResult.cs
  src/AliceInventory/Logic/Core/ProcessingResultType.cs
  src/AliceInventory/Logic/Email/InventoryEmailService.cs
  src/AliceInventory/Logic/Entry.cs
  src/AliceInventory/Logic/Error.cs
  src/AliceInventory/Logic/Extensions.cs
  src/AliceInventory/Logic/ICommandCache.cs
  src/AliceInventory/Logic/InventoryDialogService.cs
  src/AliceInventory/Logic/Parser/CommandTemplate.cs
  src/AliceInventory/Logic/Parser/CommandTemplateWithEmail.cs
  src/AliceInventory/Logic/Parser/CommandTemplateWithEntry.cs
  src/AliceInventory/Logic/Parser/CommandTemplateWithSingleEntry.cs
  src/AliceInventory/Logic/Parser/IInputParserService.cs
  src/AliceInventory/Logic/Parser/InputParserService.cs
  src/AliceInventory/Logic/Parser/ParsedCommand.cs
  src/AliceInventory/Logic/Parser/ParsedEntry.cs
  src/AliceInventory/Logic/Parser/ParsedPhraseType.cs
  src/AliceInventory/Logic/Parser/RegexHelper.cs
  src/AliceInventory/Logic/ProcessingResult.cs
  src/AliceInventory/Startup.cs
Labels: bug, data, enhancement, logic, Алиса

#90 Fixed bugs with list rendering and entry deletion logic.
  src/AliceInventory.UnitTests/InventoryDialogServiceTests.cs
  src/AliceInventory/Controllers/Extensions.cs
  src/AliceInventory/Logic/Core/InventoryDialogService.cs
Labels: bug

#92 Removed example folder from repository.
  example/ConsoleApp/ConsoleApp.csproj
  example/ConsoleApp/Program.cs
  example/WebAPI/AliceTestApi.sln
  example/WebAPI/TestApi.IntegrationTests/TestApi.IntegrationTests.csproj
  example/WebAPI/TestApi.IntegrationTests/UnitTest1.cs
  example/WebAPI/TestApi/Controllers/ValuesController.cs
  example/WebAPI/TestApi/Program.cs
  example/WebAPI/TestApi/Properties/launchSettings.json
  example/WebAPI/TestApi/Startup.cs
  example/WebAPI/TestApi/TestApi.csproj
  example/WebAPI/TestApi/UserInput.cs
  example/WebAPI/TestApi/appsettings.Development.json
  example/WebAPI/TestApi/appsettings.json
Labels: bug

#93 Feature/more command
  src/AliceInventory.UnitTests/InputParserServiceTest.cs
  src/AliceInventory.UnitTests/InventoryDialogServiceTests.cs
  src/AliceInventory/Logic/Parser/InputParserService.cs
  src/AliceInventory/Logic/Parser/RegexHelper.cs
Labels: bug

#95 Fixed unit of measure rendering in email.
  src/AliceInventory/Logic/Extensions.cs
Labels: bug

#99 mongo
  src/AliceInventory.IntegrationTests/InventoryControllerTest.cs
  src/AliceInventory.IntegrationTests/TestConfigurationService.cs
  src/AliceInventory.UnitTests/InventoryDialogServiceTests.cs
  src/AliceInventory/AliceInventory.csproj
  src/AliceInventory/Data/DictionaryUserDataStorage.cs
  src/AliceInventory/Data/Entry.cs
  src/AliceInventory/Data/IUserDataStorage.cs
  src/AliceInventory/Data/MongoUserDataStorage.cs
  src/AliceInventory/Data/User.cs
  src/AliceInventory/Data/UserData.cs
  src/AliceInventory/Logic/Configuration/ConfigurationService.cs
  src/AliceInventory/Logic/Configuration/IConfigurationService.cs
  src/AliceInventory/Logic/Core/Errors/EmptyEntryListError.cs
  src/AliceInventory/Logic/Core/Errors/MailIsEmptyError.cs
  src/AliceInventory/Logic/Core/Errors/NotEnoughEntryToDeleteError.cs
  src/AliceInventory/Logic/Core/Exceptions/UnexpectedNullOrEmptyStringException.cs
  src/AliceInventory/Logic/Core/Exceptions/UnexpectedTypeException.cs
  src/AliceInventory/Logic/Core/IInventoryDialogService.cs
  src/AliceInventory/Logic/Core/InventoryDialogService.cs
  src/AliceInventory/Logic/Core/ProcessingCommand.cs
  src/AliceInventory/Logic/Core/ProcessingCommandType.cs
  src/AliceInventory/Logic/Core/ProcessingResultType.cs
  src/AliceInventory/Logic/Email/EmailHost.cs
  src/AliceInventory/Logic/Email/EmailService.cs
  src/AliceInventory/Logic/Email/IInventoryEmailService.cs
  src/AliceInventory/Logic/Email/InventoryEmailService.cs
  src/AliceInventory/Logic/Entry.cs
  src/AliceInventory/Logic/Error.cs
  src/AliceInventory/Logic/Extensions.cs
  src/AliceInventory/Logic/Parser/CommandTemplate.cs
  src/AliceInventory/Logic/Parser/IInputParserService.cs
  src/AliceInventory/Logic/Parser/InputParserService.cs
  src/AliceInventory/Logic/Parser/ParsedCommand.cs
  src/AliceInventory/Logic/Parser/ParsedEntry.cs
  src/AliceInventory/Logic/Parser/ParsedPhraseType.cs
  src/AliceInventory/Logic/Parser/RegexHelper.cs
  src/AliceInventory/Logic/UnitOfMeasure.cs
  src/AliceInventory/Startup.cs
Labels: enhancement

#101 Fixed saving email.
  src/AliceInventory/Data/MongoUserDataStorage.cs
  src/AliceInventory/Data/User.cs
Labels: bug

#103 Added tracing with jaeger
  src/AliceInventory.IntegrationTests/AliceInventory.IntegrationTests.csproj
  src/AliceInventory.IntegrationTests/InventoryControllerTest.cs
  src/AliceInventory.IntegrationTests/TestConfigurationService.cs
  src/AliceInventory.IntegrationTests/TestTracingProvider.cs
  src/AliceInventory/AliceInventory.csproj
  src/AliceInventory/Controllers/InventoryController.cs
  src/AliceInventory/Logic/Configuration/ConfigurationService.cs
  src/AliceInventory/Logic/Configuration/IConfigurationService.cs
  src/AliceInventory/Logic/Parser/RegexHelper.cs
  src/AliceInventory/Logic/Tracing/ITracingProvider.cs
  src/AliceInventory/Logic/Tracing/JaegerTracingProvider.cs
  src/AliceInventory/Startup.cs
Labels: enhancement

#104 More details in tracing.
  src/AliceInventory/Controllers/InventoryController.cs
Labels: enhancement

#105 Fix for production email saving problem
  src/AliceInventory/Controllers/InventoryController.cs
Labels: bug

#108 Input processing fixed
  src/AliceInventory.UnitTests/InputParserServiceTest.cs
  src/AliceInventory.UnitTests/InventoryDialogServiceTests.cs
  src/AliceInventory/Controllers/Extensions.cs
  src/AliceInventory/Controllers/InventoryController.cs
  src/AliceInventory/Logic/Core/IInventoryDialogService.cs
  src/AliceInventory/Logic/Core/InventoryDialogService.cs
  src/AliceInventory/Logic/Parser/CommandTemplate.cs
  src/AliceInventory/Logic/Parser/CommandTemplateWithEmail.cs
  src/AliceInventory/Logic/Parser/CommandTemplateWithEntry.cs
  src/AliceInventory/Logic/Parser/IInputParserService.cs
  src/AliceInventory/Logic/Parser/InputParserService.cs
  src/AliceInventory/Logic/Parser/RegexHelper.cs
  src/AliceInventory/Logic/UserInput.cs
Labels: bug

#110 Fixed mail deletion
  src/AliceInventory/Data/MongoUserDataStorage.cs
Labels: bug
