Repository vkamiansky/yandex-dialogs-inventory, pull requests merged in 2019-06, with the labels that each got.

#62 Package dependencies update.
  src/AliceInventory.IntegrationTests/AliceInventory.IntegrationTests.csproj
  src/AliceInventory.UnitTests/AliceInventory.UnitTests.csproj
  src/AliceInventory/AliceInventory.csproj
Labels: enhancement

#63 Mail sending and some other changes
  src/AliceInventory.IntegrationTests/InventoryControllerTest.cs
  src/AliceInventory.IntegrationTests/TestConfigurationService.cs
  src/AliceInventory.UnitTests/AliceResponseRenderTest.cs
  src/AliceInventory.UnitTests/InputParserServiceTest.cs
  src/AliceInventory.UnitTests/InventoryDialogServiceTests.cs
  src/AliceInventory/Controllers/AliceResponseRender/AliceResponseRendererHelper.cs
  src/AliceInventory/Controllers/AliceResponseRender/ResponseFormat.cs
  src/AliceInventory/Controllers/AliceResponseRender/ResponseTemplate.cs
  src/AliceInventory/Controllers/AliceResponseRender/TextAndSpeechTemplate.cs
  src/AliceInventory/Controllers/InventoryController.cs
  src/AliceInventory/Data/DictionaryStorage.cs
  src/AliceInventory/Data/DictionaryUserDataStorage.cs
  src/AliceInventory/Data/Entry.cs
  src/AliceInventory/Data/IInventoryStorage.cs
  src/AliceInventory/Data/IUserDataStorage.cs
  src/AliceInventory/Data/UserData.cs
  src/AliceInventory/Logic/Email/AliceEmailService.cs
  src/AliceInventory/Logic/Email/EmailHost.cs
  src/AliceInventory/Logic/Email/EmailService.cs
  src/AliceInventory/Logic/Email/IInventoryEmailService.cs
  src/AliceInventory/Logic/Email/InventoryEmailService.cs
  src/AliceInventory/Logic/Entry.cs
  src/AliceInventory/Logic/Extensions.cs
  src/AliceInventory/Logic/InputProcessingCommand.cs
  src/AliceInventory/Logic/InputProcessingResult.cs
  src/AliceInventory/Logic/InventoryDialogService.cs
  src/AliceInventory/Logic/Parser/CommandTemplate.cs
  src/AliceInventory/Logic/Parser/CommandTemplateWithEntry.cs
  src/AliceInventory/Logic/Parser/CommandTemplateWithSingleEntry.cs
  src/AliceInventory/Logic/Parser/InputParserService.cs
  src/AliceInventory/Logic/Parser/RegexHelper.cs
  src/AliceInventory/Logic/SingleEntry.cs
  src/AliceInventory/Startup.cs
Labels: analysis, data, Алиса

#71 Certificate check disabled for testing purposes.
  src/AliceInventory/Logic/Email/EmailService.cs
Labels: bug

#80 Changed help and greeting message texts.
  src/AliceInventory/Controllers/AliceResponseRender/AliceResponseRendererHelper.cs
  src/AliceInventory/Logic/Email/InventoryEmailService.cs
Labels: enhancement

#79 Parser update
  src/AliceInventory.UnitTests/InputParserServiceTest.cs
  src/AliceInventory/Logic/Parser/InputParserService.cs
  src/AliceInventory/Logic/Parser/RegexHelper.cs
Labels: enhancement
